### ISSUE TITLE
Ability to set a custom path for the multisig client

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bmultisig#15]
Right now `path` is hardcoded into the client, no matter what is passed to options (https://github.com/bcoin-org/bmultisig/blob/master/lib/client.js#L20). It would be nice if we could setup a client to access a custom path. This is possible with the default client in `bclient` and useful in bPanel where we use the clients to send requests to the proxy server.

**Comment by nodar-chkuaselidze** [comment]
Currently there are two paths.
1. For wallet
2. For multisig wallet

Most likely they are like `/` and `/multisig`.
Do you want to configure them totally separately ?

**Comment by bucko13** [comment]
In the bpanel-utils clients we use bclient to do calls to our proxy backend which makes calls to the node. For the wallet and node we can set a custom path so that using bclient we can make calls to `bwallet` and `bcoin` respectively (they can be anything we want but that is the route we are using to catch the requests on th server). For bmultisig it has to be `multisig` though. 

https://github.com/bpanel-org/bpanel-utils/blob/master/lib/clients.js
