### ISSUE TITLE
GET proposal MTX Txs

### ISSUE THREAD

**Issue by tynes** [bcoin-org/bmultisig#38]
https://github.com/bcoin-org/bmultisig/blob/master/lib/http.js#L487

I see that the `txs` variable is never populated and will always return `null` in the response json.
Is there something that you intended to do with that value? I feel like it would be a good place to include coin objects for each input

**Comment by tynes** [comment]
Each input does already come with a coin object in it, so were you thinking that the list of txs could be `TX` objects for each input to easily map to `LedgerTXInputs`?

**Comment by nodar-chkuaselidze** [comment]
yes, that was my intention but never got to it. I was going to include Full previous transactions on request so you can do signing more easily. Actually this API can be polished further to allow same functionality in bcoin wallet as well.

**Comment by tynes** [comment]
This feature was merged, so close this
