### ISSUE TITLE
cosignerPath not used?

### ISSUE THREAD

**Issue by BluSyn** [bcoin-org/bmultisig#46]
Currently there is a `cosignerPath` field passed in on wallet join.
It does not appear this value is returned at any point.

It should return in the list of `cosigners`, along with their xpubs. This is useful for hardware wallets to know what the path is for each cosigner.

Additionally, I do not think it is necessary to save the entire path in the DB. The only part of the path that is "non-deterministic" is the `purpose`, since there are several different HD schemes (44, 49, 84, etc.), and likely more in the future.

I propose removing `cosignerPath`, and adding a `purpose` (uint) field, that is then returned with the list of cosigners.

**Comment by tynes** [comment]
I agree with the proposal and would like to add the idea of including a `fingerprint` field as well.
The fingerprint is used in bip174 (https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) and is 
the fingerprint of the master public key. I believe the path to the exact key can then be reconstructed by:

`cosigner.fingerprint/cosigner.purpose/coinTypes[network]'/HDPublicKey.childIndex/proposal.branch/proposal.index`

The fingerprint replaces the `m`

**Comment by nodar-chkuaselidze** [comment]
I decided to go with cosignerPath in case there's some non-standard derivation path that still uses same `account` level derivation. But I guess stricter better for users "security" from accidental xpub usage. (I don't think many use their custom derivation paths (even though it makes sense in some cases)).

Also cosignerPath is optional, you may use it for your own convenience (but purpose make sense as well if optional?). Fingerprint is same, it can be used for convenience, so you don't use different master key accidentally and be confused why signatures don't work.

So: (master fingerprint, purpose, childIndex) tuple can give you good enough confidence for signing. (Child index can be recovered from the xpub and indexed).
